packages = ["pydantic", "dist/infinite_zork-0.1.0-py3-none-any.whl"]

[files]
"./content/full_map.json" = "./content/full_map.json"
#
#[files]
#"dist/infinite_zork-0.1.0-py3-none-any.whl" = "infinite_zork-0.1.0-py3-none-any.whl"
#
